-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 16:30:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema photohub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema photohub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `photohub` DEFAULT CHARACTER SET utf8 ;
USE `photohub` ;

-- -----------------------------------------------------
-- Table `photohub`.`User_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photohub`.`User_info` (
  `idUser_info` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `birthday` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser_info`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photohub`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photohub`.`Users` (
  `Id_users` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NULL,
  UNIQUE INDEX `Id_users_UNIQUE` (`Id_users` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `Userscol_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`Id_users`),
  CONSTRAINT `users`
    FOREIGN KEY (`Id_users`)
    REFERENCES `photohub`.`User_info` (`idUser_info`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photohub`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photohub`.`Subscription` (
  `idSubscriber` INT NOT NULL,
  `Subscribe_to` VARCHAR(45) NULL,
  `Subscription_date` DATETIME(1) NULL,
  PRIMARY KEY (`idSubscriber`),
  UNIQUE INDEX `idSubscriber_UNIQUE` (`idSubscriber` ASC) VISIBLE,
  UNIQUE INDEX `Subscribe_to_UNIQUE` (`Subscribe_to` ASC) VISIBLE,
  UNIQUE INDEX `Subscription_date_UNIQUE` (`Subscription_date` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`idSubscriber`)
    REFERENCES `photohub`.`Users` (`Id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `subsribe_to`
    FOREIGN KEY ()
    REFERENCES `photohub`.`Subscription` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photohub`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photohub`.`Photo` (
  `idPhoto` INT NOT NULL,
  `path` VARCHAR(45) NULL,
  `createdate` DATETIME(1) NULL,
  `id_user` INT NULL,
  `like_count` INT NULL,
  `history` TINYINT NULL,
  PRIMARY KEY (`idPhoto`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photohub`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photohub`.`comments` (
  `id_comments` INT NOT NULL,
  `parent_id` INT NULL,
  `id_photo` INT NULL,
  `id_user` INT NULL,
  `create_date` DATETIME(1) NULL,
  `message` VARCHAR(45) NULL,
  `like_count` INT NULL,
  PRIMARY KEY (`id_comments`),
  UNIQUE INDEX `id_comments_UNIQUE` (`id_comments` ASC) VISIBLE,
  INDEX `comments_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `comments`
    FOREIGN KEY (`parent_id`)
    REFERENCES `photohub`.`comments` (`id_comments`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photohub`.`Users_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photohub`.`Users_like` (
  `idUsers_like` INT NOT NULL,
  `object_id` INT NOT NULL,
  PRIMARY KEY (`idUsers_like`),
  UNIQUE INDEX `object_id_UNIQUE` (`object_id` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`idUsers_like`)
    REFERENCES `photohub`.`Users` (`Id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `photo`
    FOREIGN KEY (`object_id`)
    REFERENCES `photohub`.`Photo` (`idPhoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comm`
    FOREIGN KEY (`object_id`)
    REFERENCES `photohub`.`comments` (`id_comments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photohub`.`Hashtag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photohub`.`Hashtag` (
  `idHashtag` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`idHashtag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photohub`.`hash_2_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photohub`.`hash_2_photo` (
  `idhash_2_photo` INT NOT NULL,
  `id_photo` INT NULL,
  PRIMARY KEY (`idhash_2_photo`),
  INDEX `hashphoto_idx` (`id_photo` ASC) VISIBLE,
  CONSTRAINT `hashtag`
    FOREIGN KEY (`idhash_2_photo`)
    REFERENCES `photohub`.`Hashtag` (`idHashtag`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hashphoto`
    FOREIGN KEY (`id_photo`)
    REFERENCES `photohub`.`Photo` (`idPhoto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photohub`.`Repost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photohub`.`Repost` (
  `user_id` INT NULL,
  `photo_id` INT NULL,
  `author_post` INT NULL,
  INDEX `repost_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `photo_id_idx` (`photo_id` ASC) VISIBLE,
  CONSTRAINT `repost_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `photohub`.`Users` (`Id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `photo_id`
    FOREIGN KEY (`photo_id`)
    REFERENCES `photohub`.`Photo` (`idPhoto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `uuthor_post`
    FOREIGN KEY (`user_id`)
    REFERENCES `photohub`.`Users` (`Id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photohub`.`direct_dialog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photohub`.`direct_dialog` (
  `message` VARCHAR(45) NULL,
  `id_author` INT NULL,
  `create_date` DATETIME(1) NULL,
  `to_user` INT NULL,
  `read` TINYINT NULL,
  INDEX `direct_dialoguser_idx` (`id_author` ASC) VISIBLE,
  CONSTRAINT `direct_dialoguser`
    FOREIGN KEY (`id_author`)
    REFERENCES `photohub`.`Users` (`Id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
